# Generated by Django 4.0.1 on 2022-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
